import { createSlice } from "@reduxjs/toolkit";

// Define the initial state for the slice
const initialState = {
  user: JSON.parse(localStorage.getItem("auth")) || null,
  loading: false,
  darkMode: false, // Add darkMode state
};

// Create a slice for the rootReducer
const rootSlice = createSlice({
  name: "rootReducer",
  initialState,
  reducers: {
    // Define your reducers here
    showLoading(state, action) {
      return {
        ...state,
        loading: true,
      };
    },
    hideLoading(state, action) {
      return {
        ...state,
        loading: false,
      };
    },
    toggleTheme(state) {
      state.darkMode = !state.darkMode; // Toggle dark mode
    },
    setUser(state, action) {
      state.user = action.payload; // Set userId based on action payload
    },
  },
});

// Export actions generated by createSlice
export const { showLoading, hideLoading, toggleTheme, setUser } =
  rootSlice.actions;

// Export the reducer to be used in the store
export default rootSlice.reducer;
